// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/todo/auth
package auth

import (
	gcr1_examples "github.com/chakrit/rpc/examples"
	gcre2_todo "github.com/chakrit/rpc/examples/todo"
)

type AuthRequest struct {
	Provider string `json:"provider" yaml:"provider"`
	Secret   string `json:"secret" yaml:"secret"`
	Username string `json:"username" yaml:"username"`
}

type AuthResponse struct {
	Failure *gcr1_examples.Failure `json:"failure" yaml:"failure"`
	User    *gcre2_todo.User       `json:"user" yaml:"user"`
}

type Interface interface {
	Authenticate(*AuthRequest) (*AuthResponse, error,
	)
	Current() (*gcre2_todo.User, error,
	)
}
