// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/todo/auth
package Auth

import (
	rpc_root "github.com/chakrit/rpc/examples"
	rpc_todo "github.com/chakrit/rpc/examples/todo"
)

type AuthRequest struct {
	Provider string `json:"provider" yaml:"provider" db:"provider"`
	Secret   string `json:"secret" yaml:"secret" db:"secret"`
	Username string `json:"username" yaml:"username" db:"username"`
}

type AuthResponse struct {
	Failure *rpc_root.Failure `json:"failure" yaml:"failure" db:"failure"`
	User    *rpc_todo.User    `json:"user" yaml:"user" db:"user"`
}

type Interface interface {
	Authenticate(*AuthRequest) (*AuthResponse, error,
	)
	Current() (*rpc_todo.User, error,
	)
}
