// <auto-generated />
//
// expected import: github.com/chakrit/rpc/todo/api/client
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"time"

	rpc_root "github.com/chakrit/rpc/todo/api"
)

var (
	_ context.Context = nil
	_ time.Time       = time.Time{}
)

// github.com/chakrit/rpc/todo/api
var _ rpc_root.Interface = Client_rpc_root{}

type Client_rpc_root struct {
	*Client
}

func (c *Client_rpc_root) initialize(client *Client) {
	c.Client = client
}

func (c Client_rpc_root) Create(
	ctx context.Context,
	arg0 string,
) (
	out0 *rpc_root.TodoItem,
	err error,
) {
	payload := []interface{}{arg0}

	buf := &bytes.Buffer{}
	if err = json.NewEncoder(buf).Encode(payload); err != nil {
		return
	}

	var req *http.Request
	req, err = http.NewRequest("POST", "http://"+c.Client.Options.Addr+"/api/Create", buf)
	if err != nil {
		return
	}

	req = req.WithContext(ctx)

	var resp *http.Response
	resp, err = c.HTTPClient.Do(req)
	if err != nil {
		return
	}

	returns := [1]interface{}{&out0}
	result := &Result{}
	result.Returns = returns[:]

	if resp.Body != nil {
		defer resp.Body.Close()

		if err = json.NewDecoder(resp.Body).Decode(result); err != nil {
			return
		}
	}

	if result.Error != nil {
		err = result.Error
	}
	return
}
func (c Client_rpc_root) Destroy(
	ctx context.Context,
	arg0 int64,
) (
	out0 *rpc_root.TodoItem,
	err error,
) {
	payload := []interface{}{arg0}

	buf := &bytes.Buffer{}
	if err = json.NewEncoder(buf).Encode(payload); err != nil {
		return
	}

	var req *http.Request
	req, err = http.NewRequest("POST", "http://"+c.Client.Options.Addr+"/api/Destroy", buf)
	if err != nil {
		return
	}

	req = req.WithContext(ctx)

	var resp *http.Response
	resp, err = c.HTTPClient.Do(req)
	if err != nil {
		return
	}

	returns := [1]interface{}{&out0}
	result := &Result{}
	result.Returns = returns[:]

	if resp.Body != nil {
		defer resp.Body.Close()

		if err = json.NewDecoder(resp.Body).Decode(result); err != nil {
			return
		}
	}

	if result.Error != nil {
		err = result.Error
	}
	return
}
func (c Client_rpc_root) List(
	ctx context.Context,
) (
	out0 []*rpc_root.TodoItem,
	err error,
) {
	payload := []interface{}{}

	buf := &bytes.Buffer{}
	if err = json.NewEncoder(buf).Encode(payload); err != nil {
		return
	}

	var req *http.Request
	req, err = http.NewRequest("POST", "http://"+c.Client.Options.Addr+"/api/List", buf)
	if err != nil {
		return
	}

	req = req.WithContext(ctx)

	var resp *http.Response
	resp, err = c.HTTPClient.Do(req)
	if err != nil {
		return
	}

	returns := [1]interface{}{&out0}
	result := &Result{}
	result.Returns = returns[:]

	if resp.Body != nil {
		defer resp.Body.Close()

		if err = json.NewDecoder(resp.Body).Decode(result); err != nil {
			return
		}
	}

	if result.Error != nil {
		err = result.Error
	}
	return
}

type Result struct {
	Error   error         `json:"error"`
	Returns []interface{} `json:"returns"`
}

type Client struct {
	Options
	Client_rpc_root

	HTTPClient *http.Client
}

type Options struct {
	Addr string
}

func New(opts *Options) *Client {
	client := &Client{
		Options:         *opts,
		Client_rpc_root: Client_rpc_root{},
		HTTPClient:      &http.Client{},
	}
	client.Client_rpc_root.initialize(client)
	return client
}
