// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/todo/system
package System

import (
	rpc_root "github.com/chakrit/rpc/examples"
)

type Interface interface {
	Status() (*rpc_root.Failure, error,
	)
}
