// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/todo/system
package system

import (
	"context"
	"encoding/json"
	"math"

	rpc_root "github.com/chakrit/rpc/examples"
)

var (
	_ context.Context = nil
	_                 = json.Marshal
	_                 = math.Pi
)

type Interface interface {
	Status(context.Context) (*rpc_root.Failure, error,
	)
}
