// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/server
package server

import (
	"encoding/json"
	"net/http"

	rpc_root "github.com/chakrit/rpc/examples"
	rpc_todo "github.com/chakrit/rpc/examples/todo"
	rpc_todo_auth "github.com/chakrit/rpc/examples/todo/auth"

	rpc_todo_system "github.com/chakrit/rpc/examples/todo/system"
)

type Handler_rpc_root struct {
	Handler rpc_root.Interface
	Todo    Handler_rpc_todo
}

type Handler_rpc_todo struct {
	Handler rpc_todo.Interface
	Auth    Handler_rpc_todo_auth
	System  Handler_rpc_todo_system
}

type Handler_rpc_todo_auth struct {
	Handler rpc_todo_auth.Interface
}

type Handler_rpc_todo_system struct {
	Handler rpc_todo_system.Interface
}

type Result struct {
	Error   error         `json:"error"`
	Returns []interface{} `json:"returns"`
}

type Server struct {
	Options
	Handler_rpc_root
}

type Options struct {
	Addr string
}

func New(opts *Options) *Server {
	return &Server{Options: *opts}
}

func (s *Server) Listen() error {
	return http.ListenAndServe(s.Options.Addr, s.HTTPHandler())
}

func (s *Server) HTTPHandler() http.Handler {
	mux := http.NewServeMux()
	s.register_rpc_root(mux, s.Handler_rpc_root)
	return mux
}

func (s *Server) register_rpc_root(
	mux *http.ServeMux,
	handler Handler_rpc_root,
) *http.ServeMux {

	s.register_rpc_todo(mux, handler.Todo)
	return mux
}

func (s *Server) register_rpc_todo(
	mux *http.ServeMux,
	handler Handler_rpc_todo,
) *http.ServeMux {

	s.register_rpc_todo_auth(mux, handler.Auth)
	s.register_rpc_todo_system(mux, handler.System)
	return mux
}

func (s *Server) register_rpc_todo_auth(
	mux *http.ServeMux,
	handler Handler_rpc_todo_auth,
) *http.ServeMux {

	mux.HandleFunc("/examples/todo/auth/Authenticate", func(resp http.ResponseWriter, req *http.Request) {
		var err error
		resp.Header().Set("Content-Type", "application/json")

		var arg0 *rpc_todo_auth.AuthRequest
		args := [1]interface{}{
			&arg0,
		}

		if req.Body != nil {
			if err := json.NewDecoder(req.Body).Decode(&args); err != nil {
				resp.WriteHeader(400)
				renderError(resp, err)
				return
			}
		}

		var out0 *rpc_todo_auth.AuthResponse
		out0, err = handler.Handler.Authenticate(
			req.Context(), arg0)
		result := &Result{
			Error: err,
			Returns: []interface{}{
				out0,
			},
		}

		bytes, err := json.Marshal(result)
		if err != nil {
			resp.WriteHeader(500)
			renderError(resp, err)
		}

		resp.WriteHeader(200)
		_, _ = resp.Write(bytes)
	})

	mux.HandleFunc("/examples/todo/auth/Current", func(resp http.ResponseWriter, req *http.Request) {
		var err error
		resp.Header().Set("Content-Type", "application/json")

		var out0 *rpc_todo.User
		out0, err = handler.Handler.Current(
			req.Context())
		result := &Result{
			Error: err,
			Returns: []interface{}{
				out0,
			},
		}

		bytes, err := json.Marshal(result)
		if err != nil {
			resp.WriteHeader(500)
			renderError(resp, err)
		}

		resp.WriteHeader(200)
		_, _ = resp.Write(bytes)
	})

	return mux
}

func (s *Server) register_rpc_todo_system(
	mux *http.ServeMux,
	handler Handler_rpc_todo_system,
) *http.ServeMux {

	mux.HandleFunc("/examples/todo/system/Status", func(resp http.ResponseWriter, req *http.Request) {
		var err error
		resp.Header().Set("Content-Type", "application/json")

		var out0 *rpc_root.Failure
		out0, err = handler.Handler.Status(
			req.Context())
		result := &Result{
			Error: err,
			Returns: []interface{}{
				out0,
			},
		}

		bytes, err := json.Marshal(result)
		if err != nil {
			resp.WriteHeader(500)
			renderError(resp, err)
		}

		resp.WriteHeader(200)
		_, _ = resp.Write(bytes)
	})

	return mux
}

func renderError(resp http.ResponseWriter, e error) {
	result := &Result{
		Error:   e,
		Returns: nil,
	}

	bytes, err := json.Marshal(result)
	if err != nil {
		_, _ = resp.Write([]byte(`{"error":"json processing error"}`))
	} else {
		_, _ = resp.Write(bytes)
	}
}
