// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples/todo
package todo

import (
	time "time"
)

type User struct {
	Ctime    time.Time `json:"ctime" yaml:"ctime"`
	Username string    `json:"username" yaml:"username"`
}

type Interface interface {
}
