// <auto-generated />
//
// expected import: github.com/chakrit/rpc/todo/api
package api

type TodoItem struct {
	Description string `json:"description" yaml:"description" db:"description"`
	Done        bool   `json:"done" yaml:"done" db:"done"`
	ID          string `json:"id" yaml:"id" db:"id"`
}

type Interface interface {
	Destroy(string) (*TodoItem, error,
	)
	List() ([]*TodoItem, error,
	)
	Retrieve(string) (*TodoItem, error,
	)
	Update(string, *TodoItem) (*TodoItem, error,
	)
}
