// <auto-generated />
//
// expected import: github.com/chakrit/rpc/examples
package examples

type Failure struct {
	Code        string `json:"code" yaml:"code" db:"code"`
	Description string `json:"description" yaml:"description" db:"description"`
}

type Interface interface {
}
